export const GET_COUNTER_TABLE = "GET_COUNTER_TABLE";
export const SET_COUNTER_TABLE = "SET_COUNTER_TABLE";
export const GET_COUNTER_TYPE = "GET_COUNTER_TYPE";
export const SET_SUCCESS = "SET_SUCCESS";
export const SET_COUNTER_NUMBER = "SET_COUNTER_NUMBER";
export const GENERATE_COUNTER_NUMBER = "GENERATE_COUNTER_NUMBER";
export const GET_COUNTER_NUMBER = "GET_COUNTER_NUMBER";
export const ADD_LOBBY_CALLBACK = "ADD_LOBBY_CALLBACK";
export const LOBBY_TABLE = "LOBBY_TABLE";
export const ADD_LOBBY_CALLBACK_MAIN = "ADD_LOBBY_CALLBACK_MAIN";

export const SET_SNACKBAR = "SET_SNACKBAR";
export const SET_TABLE_CLICK = "SET_TABLE_CLICK";
export const USERLIST = "USERLIST";
export const TABLE_USERLIST = "TABLE_USERLIST";
