export const GET_DEFAULTS = "GET_DEFAULTS";
export const GET_USER_INFO = "GET_USER_INFO";
export const GET_LOGO = "GET_LOGO";
export const GET_NAME = "GET_NAME";
export const SIGNALR_CONNECT_NOTIFY = "SIGNALR_CONNECT_NOTIFY";
export const SIGNALR_CONNECT_NOTIFY_MOBILE = "SIGNALR_CONNECT_NOTIFY_MOBILE";
export const NOTIFY_QUEUE = "NOTIFY_QUEUE";
export const NOTIFY_QUEUE_MOBILE = "NOTIFY_QUEUE_MOBILE";
